FROM hideojoho/anserini:0.9.5
# 作業フォルダ
WORKDIR /work
# イメージ情報
LABEL Maintainer="hideo.joho@gmail.com"
LABEL Version="1.0"
LABEL Description="Pyserini 0.9.4 with Anserini 0.9.5, Apache Lucene 8.5.2, Open JDK 11, and Ubuntu 20.04"
# Pyseriniをインストール
RUN pip3 install pyserini
